### ISSUE TITLE
Change the gallery to the gallery given in the portfolio page

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#1]
### Change this gallery 
![image](https://user-images.githubusercontent.com/92918449/206382346-590e8ba7-0cea-4c73-b287-73fd7673e86f.png)
### with the one in the portfolio page
![image](https://user-images.githubusercontent.com/92918449/206382480-da6d5470-6938-4018-b8dc-209c2612a7e2.png)

**Comment by aritroCoder** [comment]
> assign this to me
Done. You can start contributing now
