### ISSUE TITLE
Add a 3D carousel for the councils

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#2]
### Add a 3D carousel for the councils in place of this 
![image](https://user-images.githubusercontent.com/92918449/206383224-320218b8-45f9-48d3-986b-1eac3fb26373.png)

**Comment by digvijaysingh3023** [comment]
please assign me this

**Comment by rdev12** [comment]
The councils are:
Students' Welfare Board
Hostel Affairs Council
Sports Council
Students' Technical Council
House of Socio Cultural Affairs
Academic and Career Council

**Comment by kshitij01042002** [comment]
Assign me this, if it's still open?

**Comment by digvijaysingh3023** [comment]
its done ig it can be closed.
