### ISSUE TITLE
Add animations on click in navigation tab

### ISSUE THREAD

**Issue by kshitij01042002** [aritroCoder/IITP-Gymkhana#21]
#19 
Here you can see that on click of nav tabs, it just jumps to the section of the website, we can add animation for better UX.

**Comment by Anurag-Deo** [comment]
@kshitij01042002 Assigned the issue, now you can start working on it

**Comment by kshitij01042002** [comment]
Okay!

**Comment by Tushar98644** [comment]
Can i take up the issue?

**Comment by Anurag-Deo** [comment]
> 

Assigned the issue to you. You may start working

**Comment by SattyamSamania** [comment]
Hey @Anurag-Deo Can I work on this?
