### ISSUE TITLE
Minor change in Navbar

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#22]
Change the javascript of the navbar so that when it is at the top then it is transparent but when the page is scrolled, then it is like the current one.

**Comment by sidling1** [comment]
Can i work on this ?

**Comment by Pritam991** [comment]
trying to fix this bug..

**Comment by ankushj0801** [comment]
Can I work on this issue ?

**Comment by SattyamSamania** [comment]
Hey @Anurag-Deo Can I work on this issue if it is still open?
