### ISSUE TITLE
Fix the popup of the gallery

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#23]
When the image is clicked, fix the pop-up issue. The image must come as a modal on the top with a cross button. For more reference, you can see the portfolio page there the same thing is implemented.
![image](https://user-images.githubusercontent.com/92918449/208050182-4a135817-90ac-4a75-8b13-8907a072f0a1.png)

**Comment by sidling1** [comment]
Can I work on this ?

**Comment by ankushj0801** [comment]
I want to work on this please assign me this. @Anurag-Deo

**Comment by Anurag-Deo** [comment]
> 

Assigned, you may start working

**Comment by Anurag-Deo** [comment]
Fixed in the latest commit so closing the issue
