### ISSUE TITLE
Add a FAQ section on the home page

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#27]
## Add a FAQ section on the home page
Take the component as shown in the picture from the element.html file and add the questions and answer from the  doc file attatched. Make a clubbed carousel for multiple sections as described in the doc file
**Image of the element to be used:** 
![WhatsApp Image 2022-12-28 at 21 27 49](https://user-images.githubusercontent.com/92918449/210141124-58fb3816-7ece-4e41-87fd-b3f697c459e7.jpg)
**Link of the doc file to be used:** https://docs.google.com/document/d/16HNAIxnPf5bXyD7BAdA2X6Og65wyhkHC8ZHntKdewus/edit?usp=drivesdk

**Comment by SattyamSamania** [comment]
Hey @Anurag-Deo Can I work on this. Also tell me further what should I use to create this feature.

**Comment by TithiB-del** [comment]
I 
can work on this

**Comment by Anurag-Deo** [comment]
> Hey @Anurag-Deo Can I work on this. Also tell me further what should I use to create this feature.

You can use any tab layout preferred bootstrap and then inside each of the tabs create this section and add questions given in the sheet with their answers which will appear when the user expands the question by clicking on it

**Comment by SattyamSamania** [comment]
> > Hey @Anurag-Deo Can I work on this. Also tell me further what should I use to create this feature.
> 
> You can use any tab layout preferred bootstrap and then inside each of the tabs create this section and add questions given in the sheet with their answers which will appear when the user expands the question by clicking on it

@Anurag-Deo So I have to add in every .html file?

**Comment by SattyamSamania** [comment]
> > Hey @Anurag-Deo Can I work on this. Also tell me further what should I use to create this feature.
> 
> You can use any tab layout preferred bootstrap and then inside each of the tabs create this section and add questions given in the sheet with their answers which will appear when the user expands the question by clicking on it

@Anurag-Deo Can I add the FAQ Section above footer in the index.html file?
