### ISSUE TITLE
Add a know more button for the club carousel

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#4]
### Add a know more button for the club carousel which will redirect to the stc webpage or hosca webpage.
![image](https://user-images.githubusercontent.com/92918449/206383884-4beb92a1-f45f-4f61-ada8-7303a096004f.png)

**Comment by aritroCoder** [comment]
STC webpage: https://stc.iitp.ac.in/
HoSCA  Webpage: https://www.iitp.ac.in/hosca/

**Comment by Anurag-Deo** [comment]
The button added is not responsive. In the mobile view, it is not in the center too. Also, you need to see the positioning of the button in the mobile view.
