### ISSUE TITLE
Add one more carousel for the hosca clubs

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#5]
### Add one more carousel similar to the already added one below it. Change the name of the first one to the STC Clubs and other to HOSCA Clubs.
![image](https://user-images.githubusercontent.com/92918449/206384254-7227cd30-0daa-4835-8485-9ad78facb42f.png)

**Comment by HetviSoni** [comment]
I would like to work on this issue.

**Comment by aritroCoder** [comment]
> I would like to work on this issue.

go ahead
