### ISSUE TITLE
Fix the fest image gallery

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#6]
### Fix the fest gallery try to make it a tabbed gallery if not possible then add something to sort pictures in the same gallery if not then add all the pictures to the same gallery and then add different names to different fest pictures to make them different from one another.
![image](https://user-images.githubusercontent.com/92918449/206385092-5e77b5e8-8480-4175-85d4-ed49db832416.png)

**Comment by crveda** [comment]
I would like to work on this issue .
Can you assign it to me ?

**Comment by aritroCoder** [comment]
> I would like to work on this issue . Can you assign it to me ?

Sure start working
