### ISSUE TITLE
Remove the old carousel

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#7]
### Remove this carousel from the page
![image](https://user-images.githubusercontent.com/92918449/206385269-49eb8c57-c484-49b5-a37e-58516538d4d3.png)

**Comment by itz-deepak** [comment]
assign this to me

**Comment by aritroCoder** [comment]
> assign this to me

Sure

**Comment by aritroCoder** [comment]
> assign this to me

Sorry about it, it was already solved by one of the maintainers
