### ISSUE TITLE
Change the about section of the page

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#8]
### Change the about section of the page from
![image](https://user-images.githubusercontent.com/92918449/206385406-12826e5a-b9fd-440d-8f8d-4c1b279fe5af.png)
### to 
![image](https://user-images.githubusercontent.com/92918449/206385447-9df846b3-5ed5-4d26-8954-4a7089036d9b.png)
### Make sure content is same

**Comment by aritroCoder** [comment]
Note: The component in which it is to be changed is also present in the website (at the same page). You just have to remove it, and position it in place of the original about section, and add the content of the original section

**Comment by Anurag-Deo** [comment]
> I didn't get what you are trying to say. Can you explain it a bit more?

Just you have to change the current about section to this new design ie. add the "Clubs in IITP" type component, and in the text field, just paste all the existing text from the previous section and leave the images, for now, we will provide it later.

**Comment by Ykumar1415** [comment]
i want to work on this issue

**Comment by kshitij01042002** [comment]
![image](https://user-images.githubusercontent.com/91470808/206632381-931ce026-0ca5-4fda-8fba-7ee778f82787.png)
@aritroCoder is this the thing you are expecting?

**Comment by Anurag-Deo** [comment]
> ![image](https://user-images.githubusercontent.com/91470808/206632381-931ce026-0ca5-4fda-8fba-7ee778f82787.png) @aritroCoder is this the thing you are expecting?

Create a PR it seems nice
