### ISSUE TITLE
Update the logos of the clubs and link them to their individual pages

### ISSUE THREAD

**Issue by Anurag-Deo** [aritroCoder/IITP-Gymkhana#9]
### Add logos and name of different clubs in the  club carousel from [STC website](https://stc.iitp.ac.in/index.html#clubs ) and also link then to their individual pages
![image](https://user-images.githubusercontent.com/92918449/206386215-c06a26f1-34a0-41dc-b7bf-1bd605b248e4.png)
![image](https://user-images.githubusercontent.com/92918449/206386269-e6ed4e51-b630-4811-9767-6b38ce8264e2.png)

**Comment by kshitij01042002** [comment]
Assign me this 
I can definiely work on this

**Comment by kshitij01042002** [comment]
The links should be from the live website itself right?i.e. STC website

**Comment by rdev12** [comment]
> The links should be from the live website itself right?i.e. STC website

Yup

Also, 
1. Round the corners of the tiles
2. Add a "Learn More" button in the bottom of the carousel and link it the STC website

**Comment by kshitij01042002** [comment]
![image](https://user-images.githubusercontent.com/91470808/206657267-444c98b2-3531-44be-96fc-2a8d333712e4.png)

![image](https://user-images.githubusercontent.com/91470808/206657122-2d9002ad-1d2f-4082-a16b-7fb88ec5904d.png)


Are these changes enough?
I have added all the requested feature also the learn more button redirects to specific pages of the clubs.
Club logos are loading from the **clublogos folder** created inside **img** folder and not directly from the STC website.
If it's all clear, I can raise a PR!

**Comment by Anurag-Deo** [comment]
Actually the know more button added was for the same thing so keep one of the two buttons .
Few suggested changes:
1.  Make sure the color of the button matches with the overall theme, the current color is not matching well.
2. Give a little margin to the button it is very near to the text of the cards

**Comment by kshitij01042002** [comment]
Okay works! Will fix these issues and raise a pr.
Since I'll be removing know more button should i keep button theme as black and white?
